language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  - docker --version # print the version for logging
  - docker build . -t env-test
  - docker tag env-test digibert/env-test:latest

after_success:
  - docker push digibert/env-test

deploy:
  - docker run digibert/env-test
  on: main
